# Generated by Django 2.1 on 2018-09-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreasureGram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('material', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=500)),
            ],
        ),
    ]
