# Generated by Django 2.1 on 2018-09-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Treasure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasuregram',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
