# Generated by Django 2.1 on 2018-09-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Treasure', '0002_auto_20180907_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasuregram',
            name='image',
            field=models.ImageField(upload_to='Treasure'),
        ),
    ]
