# Generated by Django 2.1 on 2018-09-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Treasure', '0003_auto_20180907_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasuregram',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
