# Generated by Django 2.1 on 2018-09-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Treasure', '0005_remove_treasuregram_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasuregram',
            name='image',
            field=models.ImageField(default=False, upload_to=''),
            preserve_default=False,
        ),
    ]
