# Generated by Django 2.1 on 2018-09-09 00:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Treasure', '0007_auto_20180907_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasuregram',
            name='user',
            field=models.ForeignKey(default=1, on_delete=True, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
