# Generated by Django 2.1.1 on 2018-09-13 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Treasure', '0009_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
